### ISSUE TITLE
Show apps icons with public link

### ISSUE THREAD

**Issue by CATERBN** [nextcloud/forms#101]
**Forms 1.0.3 on Nextcloud 16.0.5**

### Steps to reproduce
1. create a form
2. set public access
3. copy link
4. open link in non logged in browser

### Actual behaviour
Display nextcloud apps installed (without access), click on app redirct to loggin

### Expected behaviour
Don't display apps (should look the same as public share in Survey app)

### Server configuration
Nextcloud instance is installed on OVH shared host with Apache (cgi-fcgi), Php 7.1.30, Mysql 5.6.42

**Comment by doudz** [comment]
Same for me, the Poll app handle the problem better, Apps button should not be visible using public link
It's some kind of security issue since it shows what apps are installed on our NextCloud
![image](https://user-images.githubusercontent.com/1262548/69152182-43839080-0adc-11ea-82d3-854a0cf86c3f.png)

**Comment by jancborchardt** [comment]
This is a duplicate of https://github.com/nextcloud/forms/issues/4 :)
