### ISSUE TITLE
Fill out form myself

### ISSUE THREAD

**Issue by vzsze** [nextcloud/forms#1023]
**Nextcloud (please complete the following information):**
- Nextcloud-Version: [e.g. 20.0.11]
- Forms-Version: [e.g. 2.3.0]

**Is your feature request related to a problem? Please describe.**
After setting up a form, I need to fill it out myself. When opening the forn in the forms tab, I get to the form editor, but can't seem to fill out the form.

**Describe the solution you'd like**
I would like to be able to fill out a form that I created myself, too.

**Describe alternatives you've considered**
Using a separate user to create and to fill out forms. But this is often not possible.

**Comment by jotoeri** [comment]
Hey @vzsze,

if you copy the form-link, you can open it yourself in your browser. Alternatively just remove the "/edit"-part from the url.

Greets,
Jonas

@jancborchardt How do you think about a separate Link "Fill form" in the Actions on App-Navigation? Or does it become too much there then already? Or maybe even replace the copy-link button on app-navigation by a link to fill the form?

**Comment by vzsze** [comment]
Thank you for pointing out the workaround with the form-link. An UI-Item in the Actions would be nice.

**Comment by JanLikar** [comment]
Sure, it's possible to copy the link, but I think we can agree that's not really an ideal UX flow.

If the maintainers agree, I'm willing to add the button into the menu.
 
In addition to that, I would argue it makes more sense to make this view the default view when the owner clicks on the form. But that's a different story.

**Comment by jotoeri** [comment]
> In addition to that, I would argue it makes more sense to make this view the default view when the owner clicks on the form. But that's a different story.

Interesting idea. And should be not too difficult to solve: Default view is fill-view, then a button linking to edit-mode in the top-bar and in the menu. @jancborchardt @nimishavijay ?

**Comment by nimishavijay** [comment]
This sounds like a good idea. A button saying "View form" or something would be nice, that opens the form in a new tab. Google Forms and Typeform use just an eye icon for this, so I'm guessing it's a pattern now. 

![image](https://user-images.githubusercontent.com/52440189/141445682-d0c314fc-ca71-43b1-af16-36c6e06f91d0.png)
![image](https://user-images.githubusercontent.com/52440189/141445632-1bb707e0-0940-4411-9d85-08d37846362d.png)

I don't think replacing the share link button with a view button is a good idea since it's the biggest way people share forms now and if that button goes missing it might be confusing.

> I would argue it makes more sense to make this view the default view when the owner clicks on the form

This would be a good idea, but I'm worried about cases where the form has expired or something. Wouldn't defaulting to view mode show "Form has expired"? Ideally you'd be able to see the questions with an indication that the form has expired.

**Comment by jotoeri** [comment]
Hmmm,
how about sth. like this, @nimishavijay ? @jancborchardt @skjnldsv ?
With the three dot-icon, i think that would also improve the findability of the sidebar, as it is more clear, that there are more things on the form, that show up there... Ref #717 

(Hover showing the tooltip)
![grafik](https://user-images.githubusercontent.com/47433654/142288875-8ff5a1ff-1221-495a-a6d0-ade9290bf45f.png)
