### ISSUE TITLE
Share link to form non-anonymous

### ISSUE THREAD

**Issue by Nniiccooollee** [nextcloud/forms#1083]
**Describe the bug**
Non-anonymous replies in forms does not work. Whether checking anonymous responses or not, no login is required & anonymous answers are shown in the results /csv file

Aim: Before filling out the form, users have to login to nextcloud ( in our case via SSO) so that their responses are NOT anonymous.

**To Reproduce**
1. Go to a forms. 
2. Choose Share  via link AND SETTINGS anonymous responses NOT checked
3. In my (admin) form, the following text appears for the user under description: "Responses are connected to your Nextcloud account"
4. Send link to user: User is not required to Login before answering the form. No description about non-anonymity is shown. Resulsts/ CSV File shows anonymous responses

**Expected behavior**
Choose Share via link and de-select anonymous response.
Users have to logon before answering
Description text: your answers are connected to your nextcloud account.

**Screenshots**
![image](https://user-images.githubusercontent.com/95472026/144582120-250d3700-8155-412a-818d-1a1e98db119a.png)
![image](https://user-images.githubusercontent.com/95472026/144582520-04733747-b99c-479d-8ad6-1f2c722fe905.png)

**Nextcloud (please complete the following information):**
- Nextcloud-Version 21.0.5 Enterprise
- Forms-Version: Version 2.3.0 (also tried on 2.4.0 with same result)

**Desktop (please complete the following information):**
 -  Chrome 
 - Version 96.0.4664.45
 - Edge 
 - Version 96.0.1054.29

**Comment by jotoeri** [comment]
Hey Nicole,

indeed, the sharing and its wording is currently a bit confusing: Essentially, the link is always the same link, while the three options mainly restrict the access when using the link. So:
- 'Share via link' was initially called 'Public link', so the idea of this option is that the form is acessible without logging in. -> That's just what you see. ;)
- Show to all users, means that all users can access the form (either by link, or by their app-sidebar), they just have to be logged in. -> This is probably, what you want? ;)
- Choose users should be the most clear case here - Only selected Users/Groupmembers are allowed to access the form (possible by link or by app-sidebar).

- The anonymous option only determines, if we anonymise answers actively. If it is NOT checked, we store the logged in user, however if nobody is logged in (due to public sharing) we just don't have any user-account to store, which results in an 'anonymous' answer.

So for your situation:
- If i understand your requirements right, you could use the sharing to all users of the instance. Users would have to login to access the form, they don't get specifically notified, but also everybody can see the form on the sidebar of the forms-app. You can then still use the sharing-link to e.g. manually send an email to the users.
- In case you don't want everybody to see the form, you might need to create a group of users beeing allowed to see it and share with this group (or to each user individually). Then these users get notified via activity-app (if installed) and only these users can see the form on their sidebar of the forms-app. Also here, you can still use the link to notify the users manually.


Hope that clarifies it a bit? 😉 
I'm on to rework the sharing so it is more similar to the sharing of files and hopefully a bit more clear then. It might however still take a while to get it done.

Greets!
Jonas

**Comment by Nniiccooollee** [comment]
Hi Jonas,
thanks a lot for your fast reply and your clarification. 
In fact, I tried 'show all users' before but was hesistant about the fact that it appears in each users sidebar. However, it makes sense now :)

Best,
Nicole
