### ISSUE TITLE
Who do I talk to if I want a feature developed?

### ISSUE THREAD

**Issue by ilarimikkonen** [nextcloud/forms#1277]
Hi,

looks like a great app, but is missing a feature and we are in bit of a time crunch. If I want a feature developed ASAP and can pay for it, what to do?

**Comment by Chartman123** [comment]
At first you could use the feature request template and fill out all the information requested.

**Comment by ilarimikkonen** [comment]
done #1278

**Comment by jotoeri** [comment]
Ok, so @ilarimikkonen, regarding development: I honestly don't have the time to do it, maybe @Chartman123? Otherwise here a few options, that you could try:
- Contacting Nextcloud GmbH, but i'm not sure how their pricing and customer-contracts work.
- Setting a request on the forum help.nextcloud.com. There is a section for such development requests. However i must admit, that afaik they are not very often successful.
- Giving it a try yourself :upside_down_face: 

Apart from that - as pity it is - i don't have many ideas to get somebody to work on it. Sorry.

**Comment by Chartman123** [comment]
@ilarimikkonen @jotoeri Sorry, but I don't think that I'm able to do this... And I don't have that much time at the moment, too.
