### ISSUE TITLE
Question Actions leave Edit-Mode

### ISSUE THREAD

**Issue by jotoeri** [nextcloud/forms#1329]
**Current Behaviour**:
When opening question-options (required, delete), the action-button triggers the edit-mode on the question. When then clicking on e.g. required within the options, the focus jumps into the popover and edit-mode is left.

**Expected Behaviour**
We should have the actions-popover-focus within the edit-mode (incl. actions-button) again.

**Comment by jotoeri** [comment]
@raimund-schluessler, since you refactored the actions:
The actions are rendered html-wise completely apart from where the actions-button is. So clicking on the popover here, triggers a 'click-outside' of the parent.
Do you see a way to render the popover directly next to the actions-button, or maybe even as child of the button? So it would become a child again of the Actions-Parent.

**Comment by raimund-schluessler** [comment]
This was like this before the refactoring already. The actions dropdown never was a child of the actions trigger button. But what you can do is set the `container` prop of the `NcActions` component, this way, the actions popover is attached to the container given, instead of body. If you give your Actions-Parent, it should solve your problem, I think.

**Comment by jotoeri** [comment]
Ahh, nice, thank you. Didn't know there is a specific prop. ❤️ 
Will try that next week somewhen.
