### ISSUE TITLE
Scrolling on focus jumps to far down

### ISSUE THREAD

**Issue by tzugen** [nextcloud/forms#1387]
On Firefox 105:
When I edit a form and focus on a field, the scroll position jumps, so that the field is at the very bottom edge of the window.
Therefore it is being overlayed by the "Add a question button":
![Bildschirmfoto von 2022-10-24 12-46-34](https://user-images.githubusercontent.com/67737443/197508981-778f7628-19da-4e6e-a3f8-904aed5f4c7d.png)

Suggestion: Don't jump so far, substract the height of the "Add question button" from the  desired scrollpos...

**Comment by ascpial** [comment]
I'm using the latest Firefox version at the time of writing (108.0.1).
I just installed the app on my nextcloud instance (last version, 25.0.2 for nextcloud and 3.0.3 for the app) and I had the same issue.

Steps to reproduce :
- Create a new form
- Fill the description with a large body (the issue is much more visible when the description gets bigger)
- start adding options and see everything jumping up and down as you type and try to fill options

I think the software does not take in account the size of the description.

**Comment by Chartman123** [comment]
Ok, thank you for making it clearer how to reproduce the issue, I could see it here, too.
