### ISSUE TITLE
Remove the "Responses are anonymous"

### ISSUE THREAD

**Issue by jernst** [nextcloud/forms#1623]
If a form is declared to have "Anonymous responses", it will print "Responses are anonymous." right under the description of the form before the user enters the first response. Please remove this label.

Rationale: the form may be used with the general public, not just Nextcloud users on this instance. If so, such a form will often ask for name and e-mail address, confusing the user because it also says the responses are anonymous. I think what you mean is "Does not require an account on this instance." but I'm not sure that is useful information for the user. So remove appears to be the best option.

**Comment by Chartman123** [comment]
See #804

**Comment by jotoeri** [comment]
Hi Johannes,
i see your point, but please also see, that explaining the app to everybody takes quite some time, which we can not use for development then. And to keep the Issue-Tracker usable, we also have to sort out a bit, what we really want to track.
The linked PR is definitely related, since it adressed exactly that text and was made to set it's proper behaviour, which also is described in the PR.
If you explicitely select the 'anonymous responses', then we actively anonymize the responses. Thus this text is shown and definitely right. Explicitely asking for a name, but at the same time checking 'anonymous responses', is honestly not really reasonable.
If you just want to share to users who don't have a nextcloud account, then it suffices to use a public link for sharing, but you don't have to select the anonymisation. Then, public-users don't see any text, while logged in users see the resp. info-text. The latter is desired to let the user know that the data is connected.

Hope, that clarifies?
Greets,
Jonas
