### ISSUE TITLE
Form Page Header Title

### ISSUE THREAD

**Issue by taziobaker** [nextcloud/forms#1752]
**Nextcloud (please complete the following information):**
- Nextcloud-Version: [27.1.2]
- Forms-Version: [3.3.1]

**Is your feature request related to a problem? Please describe.**
Not a problem, but an aesthetic formatting. When viewing a form from a shared link, the title of the form is shown twice. One next to the Header logo and the other on top of the actual form.

**Describe the solution you'd like**
Allow the administrator to set globally the header title for all forms. And also allow form creators to change the header title on a per form basis.

**Describe alternatives you've considered**
Or change the header title to "Form".

**Additional context**
Header title refers to the title next to the header logo.

**Comment by susnux** [comment]
So this is about changing 1 (in screenshot) to "Form" or something different, because 1 and 2 are always the same title:

![image](https://github.com/nextcloud/forms/assets/1855448/c5bd0d00-e812-40fb-a3bc-20dc60627658)

@jancborchardt / @nimishavijay what do you think from a designer perspective?

**Comment by Chartman123** [comment]
I wouldn't remove the title in the top bar.

**Comment by jancborchardt** [comment]
Here are our options:
1. Keep both like it is right now: I think this is actually good since the one in the top bar stays when scrolling.
2. Change the one in the top bar to "Forms": Would fit well with the Nextcloud logo next to it basically saying "Nextcloud Forms", but it is less informative than option 1.
3. Keep only the one in the top bar and remove the other. This seems off as the top bar header is not so present. Then the page is missing a heading.
4. Keep only the one on the page: Then the header is empty. This is option 2 in worse.

Anything I missed?

> Allow the administrator to set globally the header title for all forms. And also allow form creators to change the header title on a per form basis.

We are definitely not going to introduce a setting for any of this since it is such a minute thing.

**Comment by Chartman123** [comment]
Thank you @jancborchardt for your detailed feedback.

So I'll close this as "not planned" 👍🏻

**Comment by Chartman123** [comment]
> FYI, if you closely look at the screenshot there is three times the work Optionen

Yes, but the third time is unrelated. It's the title of the first question, which we of course can't influence 😉 

> example: NextCloud Forms | Preliminary Hiring Form

Would be fine for me. @jancborchardt What do you think of this 5th option?

**Comment by jancborchardt** [comment]
5th option sounds good to me. So:

> [Logo] **Forms** · Form name

@Chartman123 can we use the middle dot as separator, and non-bold the form name there?

**Comment by Chartman123** [comment]
@jancborchardt no, there's no formatting available... we're using the `OCP\AppFramework\Http\Template\PublicTemplateResponse` where we can only pass some text via `setHeaderTitle()`
