### ISSUE TITLE
[Gratitude] Thank you for resuming the dev on this app!

### ISSUE THREAD

**Issue by agentlibre** [nextcloud/forms#226]
This is not an issue, but I feel like expressing some gratitude from time to time wouldn't hurt! ✨

Many thanks to the dev contributors who are working again on this app and made the last 1.1.1 release, and the 2.0beta!

This app has the potential to replace, even to surpass, Googleform or Typeform in many instances for all NextCloud lovers! -> to the future [1](https://github.com/nextcloud/forms/issues/34) [2](https://github.com/nextcloud/forms/issues/296) 3... 🚀

Keep up the good work! 🙏🏻

**Comment by rogercreagh** [comment]
Thank you for bringing this back to life

**Comment by splashote** [comment]
Yeah, thx a lot!

**Comment by admorgan** [comment]
Looking forward to see it this become something I use frequently.

**Comment by 7-liberal-arts** [comment]
I would also like to express my thanks.

**Comment by rakekniven** [comment]
Thank you very much!

**Comment by alexanderdd** [comment]
Absolutely thankful. This is an outstanding feature and very helpful

**Comment by born2webdesign** [comment]
Splendid! THX!

**Comment by Busterbob** [comment]
Thanks for resuming & contining support efforts for NEXTCLOUD!

**Comment by splashote** [comment]
Thanks a lot! 
I think form is a very useful app for nextcloud.

It would be great if someone would develop it continuously.

**Comment by skjnldsv** [comment]
Hello everyone!
Beta1 is out! You can find it in the appstore! Help reviewing & feedbacks appreciated :hugs: 

@lachmanfrantisek @JimmyKater @Himra @Spartachetto @ljo @AaronADev @phonon112358 @MichaelSp @agentlibre @rogercreagh @marcelklehr @fazlerabbi37 @almereyda @phonon112358 @MichaelSp

**Comment by szaimen** [comment]
> Hello everyone!
> 2.0.0 Beta1 is out! You can find it in the appstore! Help reviewing & feedbacks appreciated 

I would like to test it. Is there a way to install the beta version directly over the appstore or do I have to install it manually?

**Comment by skjnldsv** [comment]
I think you have to download the archive file manually :thinking: 
There use dto be a beta setting in nextcloud, but not sure where it went :confounded:

**Comment by szaimen** [comment]
> I think you have to download the archive file manually 
> There use dto be a beta setting in nextcloud, but not sure where it went

Hm okay, would of course lower threshold for beta app testing by a lot!

**Comment by skjnldsv** [comment]
Yeah, the appstore have an issue in quite some time now :(

**Comment by fazlerabbi37** [comment]
Hi there, not sure if it is the right place to let you know about a bug if not will open an issue for it.

For multiple choice or checkbox:
- the text for options text auto deletes last 2-3 characters
- new box for entering options only appears if you click on the previous box, if we type an option and enter the new box for option doesn't appear.

**Comment by rakekniven** [comment]
@fazlerabbi37 Not the right place, see issue title.
Please file an issue for each topic you have.

**Comment by skjnldsv** [comment]
You can also check the existing issue if the one you noticed isn't already there: #261 #296

**Comment by AaronADev** [comment]
Awesome work!

**Comment by rogercreagh** [comment]
Is there any way to install this over the top of v1.1.1 without terminal or ftp access to the server?
When will it be available through the appstore? What is the problem there?

**Comment by szaimen** [comment]
@rogercreagh https://github.com/nextcloud/server/pull/20741

**Comment by skjnldsv** [comment]
> Is there any way to install this over the top of v1.1.1 without terminal or ftp access to the server?
AH! I found the way!
It will get easier with the pull request I created, but that is for nextcloud 20.

In the meantime, you can set your server config key `updater.release.channel` to `daily`! Then head over to your apps management, update forms.
If you don'thave terminal access, youy can try th occweb apps, and run this command there: `config:system:set updater.release.channel --value 'daily'`

Don't forget to reintialise it to `stable` after! :tada:

**Comment by skjnldsv** [comment]
Keep in mind that to rollback to the previous version, you might have to wait a bit after uninstalling.
We keep a cached file for the apps list and it takes some time to invalidate and refresh. But it's a matter of 300 seconds :)

**Comment by rogercreagh** [comment]
Brilliant - thank you very much @skjnldsv. The occ-web app is a godsend for this.
Incidentally in my case the `system updater.release.channel` setting did not already exist so I simply deleted it after installing the beta. (`config:system:delete updater.release.channel`) to put things back how they were.

**Comment by skjnldsv** [comment]
> I simply deleted it after installing the beta. (`config:system:delete updater.release.channel`) to put things back how they were.

All good too! It is set to `stable` by default ;)

**Comment by ei8fdb** [comment]
Yes, thank you for resuming work on this. I appreciate it too. Good design work too @jancborchardt and all.

I'm going to try using this for some of the shorter simpler questionnaires I make for my work.

**Comment by skjnldsv** [comment]
Beta2 is out https://github.com/nextcloud/forms/releases/tag/v2.0.0-beta2
https://apps.nextcloud.com/apps/forms/releases :tada: :rocket:

**Comment by greavette** [comment]
Hello @skjnldsv , really happy with the speed of development you have put into this module.  Very much appreciated!  I just installed Beta2 and some of the issues I had with Beta1 are now resolved so good work.  I really like having the title of the survey in the bar above, the ability to move (edit) Forms after they are created!  And the ability to make some question not mandatory is awesome! 
But I do have some suggestions/bugs I've found in Beta2.  I hope this is the right place to add these comments. If you want a separate issue for each just let me know:

1.
When I first create a new Question and type in my new Question and tab twice to put my cursor in the 'Add a new answer' field, I can type in that new answer field but once I press Ok another 'Add a new answer' field does not show up below.  I need to click off the answer I just put and when I click off that first new answer field I lose the answer I entered.  Once I add in the answer again I see the new answer boxes showing up below as expected when I press answer after each answer. 

2.
I see that short answer question does not line wrap like long answer.  Although this is a short answer with less characters I would prefer the user sees their short answer line wrap and not run off the page.  

3.
version 1.1.1 had a message at the top of the survey form when the checkbox 'Anonymous Responses' was checked.  Now when I check this I see no message in Beta2.  I think it's important to have that message on the survey if that box is checked when creating a form to confirm for people we send the form too that their responses are anonymous.  

4.
When creating a question using checkboxes I would prefer to have a way to put checkboxes beside each other rather than just running vertically down the page.  For checkbox answers that are small it would like better for our usecase to have the ability to put checkboxes into two columns within that question.  I think this would make in some use cases a cleaner question.  

5.
Similar to the comment above I think it would be useful to be able to put radio button answers into horizontal instead of only vertical.  For our usecase I ask a question " How likely will you use our services again".  I then give radio buttons for 0-10 where 0 is Not likely and 10 is Highly likely.  Having this ability to put radio button questions into horizontal would look better in my opinion.

6.
One very important feature our office needs on this Forms is the ability for sharing the Forms creating process.  I'm our Nextcloud Administrator and will receive the request from the Owner to create a new Form but if the owner wants to review the results or update an existing Form He will need to ask me each time since I'm the only one who can see it.  I would like to have the ability to create Forms and share these Forms with the owner so He can update Forms and view results submitted.  

7.
Mobile use of the Forms is looking much better.  The title of the survey does not line wrap on the browser on my Chrome Browser (Android Phone) and is cut off.    

Thank you.

**Comment by greavette** [comment]
Hello @skjnldsv, I forgot to mention this bug I encountered on 1.1.1. not sure if this was fixed in your Beta versions. I was receiving the following an "Internal Server Error" error message when i shared a public link of my survey.  The fix for this was found in the following post:
https://help.nextcloud.com/t/forms-internal-server-error/74440/10

The fix was as follows:

On line ~278 you might find, inside a try…catch, the following code:

 $notification = $this->notificationMapper->findByUserAndForm($form->getId(), $this->userId);

Repace this with the following:

if($this->userId === null) {
    $notification = $this->notificationMapper->findByUserAndForm($form->getId(), '');
} else {
    $notification = $this->notificationMapper->findByUserAndForm($form->getId(), $this->userId);
}

Once I made this code change the public link worked for my survey form.

Thank you.

**Comment by jancborchardt** [comment]
Hey @greavette! :) Thanks a lot for your feedback! Could I ask you to open individual issues for your requests?

Your points 4 and 5 are covered by this issue already: **Question type "Multiple choice grid" / "Checkbox grid" (Likert scale, matrix) #356**
For the others you can open issues. :)

**Comment by pierreozoux** [comment]
I will add my gratitude to this thread :) I just tried it, the version 2 is really cool :) Thanks for the nice work!

**Comment by skjnldsv** [comment]
Hello everyone!
RC1 have been released! https://github.com/nextcloud/forms/releases/tag/v2.0.0-rc.1
Please help testing! We'd really appreciate it! Thanks again to all who helped making this 2.0 release awesome! :rocket: :heart:

**Comment by jancborchardt** [comment]
2 main new things are:
- Dropdown question type
- Summary visualization of results

Please give it a good test, and thanks for all your feedback! :)

**Comment by skjnldsv** [comment]
Forms final 2.0.0 released! :rocket: 
https://apps.nextcloud.com/apps/forms

**Comment by skjnldsv** [comment]
Forms final 2.0.0 released! :rocket: 
https://apps.nextcloud.com/apps/forms

Again, an incredible thank you to everyone involved here!
I'm sending (covid-safe) free hugs to each andn every one of you! :hugs: 
Don't forget to make reviews and feedback after you tried it so everyone can benefit from quick response times to bugs :heart:

**Comment by skjnldsv** [comment]
@greavette thanks a lot for all yout feedback, sorry I didn't saw them before! I'm almost sure lots of them are fixed already. Could you maybe have another look with the final release and open individual issues for each one that is still here? :bowing_woman:
