### ISSUE TITLE
Update Linked Spreadsheet on Submission

### ISSUE THREAD

**Issue by Arkoprovo1996** [nextcloud/forms#2437]
**Nextcloud (please complete the following information):**

-   Nextcloud-Version: 30.0.2
-   Forms-Version: 4.3.4

**Is your feature request related to a problem? Please describe.**
So, when I submit something into forms, it updates, but until I re-export to spreadsheet, the data doesn't go into the spreadsheet. Is there any wasy to do this? Also where exactly is the data staying when it is showing in submissions, but not showing up on spreadsheets?

**Describe the solution you'd like**
I'd like the data to go directly into the specified spreadsheet, when a user hits submit on the form.

**Describe alternatives you've considered**
Having to hit re-export every so hours.

**Comment by Chartman123** [comment]
@Arkoprovo1996 since 4.3.4 the spreadsheet file will be updated using a background job, so it might take some time until you see the new results in that file. This has been changed to fix some bugs. So there will be no change back to the old behaviour. But if you experience problems that the file doesn't get updated at all you might have found a new bug. Please report back if your files get updated after some time with the new submissions.
