### ISSUE TITLE
Not possible to select text of questions or replies as it enters into drag & drop

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/forms#299]
With the enh/design-fixes branch:
When you try and mark text of the questions or replies with the mouse, it doesn’t work as it enters into the drag & drop mode.

Drag & drop should only trigger on the area of the drag handle element (the full vertical part, not only the icon), but not on the question text.

@nextcloud/forms

**Comment by jancborchardt** [comment]
Due to this it’s actually even impossible to click anywhere else in the text, only the end will be selected.

**Comment by jotoeri** [comment]
I gave it a try, according to [this issue at vuedraggable.](https://github.com/SortableJS/Vue.Draggable/issues/818).

I just don't get the css-class connected right through the elements onto the draggable-property. Maybe you get this easily, @jancborchardt? Otherwise @skjnldsv tomorrow? ;)

See branch/commit [fix/draggable](https://github.com/nextcloud/forms/commit/01642f46eee13a1fe65fc01cfdd5f6a0115a897a).

![grafik](https://user-images.githubusercontent.com/47433654/80227753-63e8e580-864e-11ea-9c4e-145d55979d49.png)

**Comment by jancborchardt** [comment]
According to this: https://github.com/SortableJS/Vue.Draggable/blob/master/example/components/handle.vue#L10-L24 it’s the other way around:
- The element needs to stay `<draggable>`
- It will get a property called `handle`, in our case `handle='.question__drag-handle`

**Comment by jancborchardt** [comment]
Fixed in a commit in https://github.com/nextcloud/forms/pull/297 :)
