### ISSUE TITLE
Allow users to mark questions as optional

### ISSUE THREAD

**Issue by ei8fdb** [nextcloud/forms#353]
**Which Forms version are you running?**
v2.0.0 beta 1 (build 20200505)

**Nextcloud or ownCloud?:**
Nextcloud

## Feature request
Allow user to mark questions are optional.

## Rational
To reduce visual noise of having repeated asterisk `*` to denote a questions status as mandatory, I propose the function to allow users mark questions as optional.

This means all questions that are not denoted as optional are therefore mandatory.

## UI
As a beginning, the optional status could be denoted with the word 'optional' (with equivalent in other languages).

## Priority
Medium/High

As a user researcher who creates questionnaires having questions be mandatory/optional is a high priority.

Thoughts?

**Comment by skjnldsv** [comment]
Hey! I'm guessing you mean #135 ? :wink:

**Comment by ei8fdb** [comment]
Gah! I thought I had read all the GH issues. (Oh! I see it's closed!)

Well - yes the same as that - however the opposite:

- there will be less optional questions than mandatory (otherwise its a strange form!)
- therefore marking questions as optional means there will be less visual

I can post my comments there if it helps?

**Comment by skjnldsv** [comment]
I'll leave this one opened, beta2 is rolling out soon :)
You'll be able to update it

**Comment by jancborchardt** [comment]
Yeah, we have to simply decide for one: Either the mandatory questions get marked, or the optional ones.

Since Google Forms is the most popular competitor here, we went with that approach, and should keep doing it like that. Since it would make no sense to have 2 different ways of picking it, I’d close this request. Hope that’s understandable @ei8fdb! :)
