### ISSUE TITLE
[REQUEST] Make already chosen options unavailable

### ISSUE THREAD

**Issue by 1989gironimo** [nextcloud/forms#36]
**Which Forms version are you running?** 
1.0.3

**Nextcloud or ownCloud?:**
NC

**Nextcloud/ownCloud version:** (see Nextcloud admin page)
16.0.1.1

I'd like to use this plugin as a Doodle replacement, but Doodle has the option to disable entries, which got already chosen by another person, which is missing in Forms.

**Comment by WNYmathGuy** [comment]
Holy shit! That sounds cool and difficult to do in a form environment. 

I assumed it was something else. Like, in an order building application, I had a dropdown programmed to remove choices that were already added to the order form. The drop-down length got shorter as line items were added to the customer's order. 

There are so many applications for this idea, but it's not really a "Form" type thing I think. You have a "Pot-Luck" style gathering of people where you don't want everybody bringing bread. A set of diminishing choices is ideal. The "Gift List" registry for a special ocasion where guests are each bringing something from the list. Selection for pick-up games where the teams need to be equitably selected is an application too. I'm a Fantasy Football lover and this is core to the system of fair distribution of talent across managers. Work Tasks at a place of business are a candidate for a diminishing list of options too. 

It lends itself to a one-to-one mapping between two sets of lists. Three tables, two lists and one a relation, where the query for unselected options selects a join of the options and the relation where the subjects table field of the relation is NULL. You might need the ability to have duplicate entries in the objects table because, for example, suppose the pot-luck dinner needs an expensive item, you might have it on the list of options as two half size identical objects such that two different people share the cost of bringing the full amount needed.

**Comment by 1989gironimo** [comment]
My usecase is, that you have some dates to choose from, but it's not possible to have two persons at the same time at this date. For instance an appointment at a doctor :)

**Comment by WNYmathGuy** [comment]
@1989gironimo Their might be a solution through a shared calendar. Years ago Google in their paid apps environment would let the account creation for a shared resource. It was like an account that represented a human, but it was for something like a Board Room. We were able to make the HDTV via Chromecast into the board room's account too. So the meeting would be where remote people would join a Hangout of the board room at a given time. Any employee could schedule time in the room just by adding an event to the shared calendar. That board room account was basically an unattended account.

I think you can mimic this in Nextcloud by adding a group for sharing purposes and then include anybody that has access to that shared calendar. Guest accounts or share by email might be necessary. Even share by link is an option. Also, you would need to build repeating events to block out the closed times where people can't make an appointment. You might need a single shared resource user account for each doctor though. Theirs also a problem of the client adding time to the calendar knowing how long they should schedule an appointment for. 

Although, as of now Nextcloud doesn't have an option to warn or prevent double-booking of time on the calendar. Many work environment calendars have features to schedule a meeting where you are given access to your coworkers' calendars to find matching free times. I don't think Nextcloud has that yet either.

**Comment by affan98** [comment]
I believe the polls app on Nextcloud is meant to be a Doodle alternative.

**Comment by WNYmathGuy** [comment]
> I believe the polls app on Nextcloud is meant to be a Doodle alternative.

@affan98 is that a reply to @1989gironimo 's [https://github.com/nextcloud/forms/issues/36#issuecomment-517179894](https://github.com/nextcloud/forms/issues/36#issuecomment-517179894) ?

If so, the last time I tried experimenting in the polls app, it wouldn't knock out a choice for others after the first person picked it. The Polls app is good for getting consensus on when to plan a group event, (wedding, conference call, sporting event, Fantasy Football Draft).

**Comment by stefan123t** [comment]
+1 though I would understand if this is out of scope for forms too. Basically the forms app would need to double check either a list of options or preferably a calendar for free slots. The configurable options should be the options list (option title, description and number of possible choices per option) and/or the timeslot constraints (possible time slots, default / fixed duration, earliest, last appointment).
My personal application would be to fill a calendar of vacant room bookings, ie selection by date would be sufficient for me. But additional fields to extend could be included in the calendar entry.
Sounds a bit like a booking / reservation app to me but that could be a very useful extension of the Forms App when local NC calendars are leveraged.

**Comment by skjnldsv** [comment]
Hey! There is also an appointement app, maybe that would fit your use case best,
I don't think that is something for forms unfortunately :/
