### ISSUE TITLE
Internal Server error

### ISSUE THREAD

**Issue by rocky-III** [nextcloud/forms#365]
Hi 
the app forms does not work on my nextcloud installation.
if I try the open a public from i just get a internal Server error messege

In the logs i find this:

> [index] Error: Exception: Argument 2 passed to OCA\Forms\Db\NotificationMapper::findByUserAndForm() must be of the type string, null given, called in /var/customers/webs/web413/nextcloud/apps/forms/lib/Controller/PageController.php on line 277 at <<closure>>
> 
>     /var/customers/webs/web413/nextcloud/lib/private/AppFramework/App.php line 125
>     OC\AppFramework\Http\Dispatcher->dispatch(OCA\Forms\Controller\PageController {}, "gotoForm")
>     /var/customers/webs/web413/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
>     OC\AppFramework\App::main("OCA\Forms\Controller\PageController", "gotoForm", OC\AppFramework\ ... {}, {hash: "XzhpmU6o ... "})
>     <<closure>>
>     OC\AppFramework\Routing\RouteActionHandler->__invoke({hash: "XzhpmU6o ... "})
>     /var/customers/webs/web413/nextcloud/lib/private/Route/Router.php line 299
>     call_user_func(OC\AppFramework\ ... {}, {hash: "XzhpmU6o ... "})
>     /var/customers/webs/web413/nextcloud/lib/base.php line 1008
>     OC\Route\Router->match("/apps/forms/form/XzhpmU6o0jGcB6Ln")
>     /var/customers/webs/web413/nextcloud/index.php line 38
>     OC::handleRequest()
> 
> GET /apps/forms/form/XzhpmU6o0jGcB6Ln
> from 93.133.0.0 at 2020-05-08T10:54:03+00:00

thank for help

**Comment by jotoeri** [comment]
Hey Rocky,

thank you for reporting this. The bug itself has been tackled already, so with the next release it will be solved.
In case you need an immediate solution, @dawidol posted his solution in simple steps in issue #291.
If you want you can alternatively install current beta of Forms v2.0. Detailed steps for this are given in #349. However, keep in mind it's not released yet, so can contain other bugs.

And just for the next time - Please search in the old issues, if your problem has been reported yet, and otherwise use the Bug-Report-Template. Just makes life much easier for us. ;)

Greets,
Jonas

**Comment by rocky-III** [comment]
Thanks
