### ISSUE TITLE
Show number of responses on responses button

### ISSUE THREAD

**Issue by jotoeri** [nextcloud/forms#422]
Show number of responses on responses button like "15 responses", and in the action menu as well

**Comment by jancborchardt** [comment]
It would also be good to use the AppNavigationCounter for this additionally: https://nextcloud-vue-components.netlify.app/#/Components/App%20containers?id=appnavigationcounter
The highlighted counter could be used if there were new responses since your last check of the responses.

That way you directly have an overview of the number of responses without needing to navigate into each form or opening the menu. :) And if we have that, I would say we don’t need the count in the action menu (since the value is directly above it already), but it’s still a nice addition on the "Responses" button in the content view.
