### ISSUE TITLE
Content below jumps if a question above it switches view/edit mode

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/forms#434]
If you click into a question, the "Add question" entry appearing results in the content below it to jump down. Similarly when you exit out of edit mode, the content below jumps up.

It would be nice to prevent this by either:
- Inserting extra space below already and using that to show the "Add question" part
- Showing the "Add question" below and using negative margin to keep the whitespace between questions in view mode as it is now.

I would prefer the second option as otherwise _all_ whitespace gets increased, and it’s already enough? :)

**Comment by susnux** [comment]
So if I get this correctly this is about the jumping of the question below if you enter edit mode of a "multiple options" question like here:

Question `baz` is jumping below when `foo` is triggered.

https://user-images.githubusercontent.com/1855448/220900904-9297c3b0-2a46-4e12-9ed9-2598e00bc305.mp4

---

I think this can be easily fixed by adding a css rule like
```css
ul.question__content {
  margin-bottom: -44px;
}
```
