### ISSUE TITLE
Forms don't work well on smartphones

### ISSUE THREAD

**Issue by HugoNeveux** [nextcloud/forms#440]
I spotted some problems while trying to make a form with this app : filling the form when using a mobile phone is pretty hard. 
The design isn't responsive, form fields width is too small, and labels for radio buttons are shown with one character per line.

If it can help, I think that this error comes from the div#content element width (which is always set to 50%). I'd like to fix it, but I can't find the right file in this repository, I guess it was moved since the 1.1.1 release...

**Comment by jancborchardt** [comment]
Hi @HugoNeveux, could you show screenshots of the issue? And could you make sure you are using the latest beta of 2.0 – we made significant changes since any 1.* release. :) 

See how it should look like:

Checkboxes | Radio buttons too
-|-
![image](https://user-images.githubusercontent.com/925062/83821170-53f10680-a6ce-11ea-8a32-4d8097e54232.png) | ![image](https://user-images.githubusercontent.com/925062/83821325-62d7b900-a6ce-11ea-8eb5-3689f760c205.png)

**Comment by HugoNeveux** [comment]
Ew... I didn't use the 2.0 beta, as it wasn't in the app store, but it looks like it solved everything ! I should have tried before. Anyway, thank you (and sorry for posting a non-accurate issue) !

**Comment by jancborchardt** [comment]
Don't worry at all @HugoNeveux! :)
If you can, help by testing the beta3 and report issues if you find anything there: https://github.com/nextcloud/forms/releases
