### ISSUE TITLE
Allow formatting with Markdown

### ISSUE THREAD

**Issue by EricKerby** [nextcloud/forms#489]
- Nextcloud-Version: 19.0.0
- Forms-Version: 2.0.0-beta4

It would be helpful to allow formatting the text in the description and field names with markdown or HTML. For recent forms I created, I found myself wanted to add emphasis to some text as well as a link or two.

**Comment by skjnldsv** [comment]
@juliushaertl the dedicated component is not yet available, right? :)

**Comment by juliushaertl** [comment]
No but work in progress https://github.com/juliushaertl/nextcloud-text/ 

It already is in kind of a working state except for some node types like images, but needs some more polishing for a first release. Unfortunately I didn't have much time lately.

**Comment by skjnldsv** [comment]
It's definitely not a priority! Take your time :)

**Comment by EricKerby** [comment]
Thanks, @juliushaertl ! Providing a visual text editor component which Forms and other apps can then utilize certainly sounds like a solid approach to satisfy this enhancement request.

**Comment by bernd-wechner** [comment]
Not sure why the thumbs down from @skjnldsv  because, given formatting is not available I put the description of the form onto a PicoCMS page, no problem, and it just links to the form for completion, but I wanted badly to put in a link back from the form to the intro page as well, measly little link. Turns out it's easy enough to do with a small tweak:

```
diff --git a/src/views/Submit.vue b/src/views/Submit.vue
index 7fd055b..52981ee 100644
--- a/src/views/Submit.vue
+++ b/src/views/Submit.vue
@@ -30,7 +30,7 @@
                                </h2>
                                <!-- Do not wrap the following line between tags! `white-space:pre-line` respects `\n` but would produce additional empty first line -->
                                <!-- eslint-disable-next-line -->
-                               <p v-if="!loading && !success" class="form-desc">{{ form.description }}</p>
+                               <p v-if="!loading && !success" class="form-desc" v-html="form.description"></p>
                                <!-- Only visible if at least one question is marked as mandatory-->
                                <p v-if="mandatoryUsed && !loading && !success" class="info-mandatory">
                                        * {{ t('forms', 'Required questions') }}
```

and I'm rolling, my form introduction is rendered as HTML not text and I have my link (and if I wanted, much richer formatting but hey, I'm, content with one link for now - the form will be relevant only until October and if there's a forms update before then I can ignore it or apply it and it  clobbers my patch I can reapply it). In the meantime Nextclouds integrity check is awesome and spots that my patched build has been patched and I get the warning on the Overview page - thumbs up for Nextcloud's security there!

In the mean time there is a Nextcloud markdown editor app: https://apps.nextcloud.com/apps/files_markdown 

which  the PcioCMS app suggests and seems to wok well.; Not fro Forms of course as the description isn't in the file system as a `.md` file.

**Comment by skjnldsv** [comment]
> Of course there are always security issues raised when a user can submit HTML code for rendering

This is the reason of my thumb down. I can tell you already html will not be supported as user input by Nextcloud. :)
Sorry!

**Comment by bernd-wechner** [comment]
Nexcloud does allow some HTML. b tags, a tags both work on the PicoCMS app.

**Comment by skjnldsv** [comment]
> Nextcloud does allow some HTML. b tags, a tags both work on the PicoCMS app.

PicoCMS is not an officially supported nc app.
Like said, markdown yes, html, no.
relevant https://github.com/nextcloud/viewer/issues/499#issuecomment-679142589

**Comment by bernd-wechner** [comment]
Not offically supported? By what measure is that?

https://nextcloud.com/blog/nextcloud-introduces-easy-website-builder-for-education-edition-with-picocms/

Fanfare like this doesn't half suggest that Nextcloud are dully into it and 'officially' if you will. Is there some measure of officialness I'm missing? Just curious.

**Comment by skjnldsv** [comment]
> Not offically supported? By what measure is that?

Sorry, I should have said that PicoCMS is not an app we ship, or that I can control. The term 'supported' of course makes no sense without a support contract with us in any case. The author can decide to support some html - but at Nextcloud GmbH we won't as we consider it an unacceptable security risk.

**Comment by bernd-wechner** [comment]
So the forms app is something Nextcloud GmbH ships?

**Comment by skjnldsv** [comment]
> So the forms app is something Nextcloud GmbH ships?

Nope, but it's a featured app.
![Capture d’écran_2020-08-31_13-48-28](https://user-images.githubusercontent.com/14975046/91716847-ac7e5580-eb90-11ea-941c-85f9b5ca3ef1.png)

**Comment by jdittrich** [comment]
Agree that formatting would be nice, I'm not sure if it needs to be (full) markdown. I guess at least most of my needs would be covered by italic and bold.

**Comment by loelkes** [comment]
> Agree that formatting would be nice, I'm not sure if it needs to be (full) markdown. I guess at least most of my needs would be covered by italic and bold.

I would like to add the possibility of adding links. This is useful for something like "I accept the Terms and Conditions" with a link to the document.

**Comment by zklmtfr** [comment]
To me personally this is the most important issue of this app. I would like to structure longer descriptions. Is the missing part still in progress or are there other options to handle this? Thanks a lot :)

**Comment by demlak** [comment]
This issue is open for 1,4 years now.. it seems, Markdown and/or a WYSIWYG Editor will take more time to come..

In meantime.. how to disable "unformating HTML"?
For us, it would be a great workaround to just have HTML correctly rendered as it is.. 
nextcloud-forms converts HTML to entitys.. but in our case, this is unnecessary.
so we would like to disable this conversion. could you give me a hint, where to change the coresponding line in code, that is responsible for rendering the text? 

thx

**Comment by chris2k20** [comment]
Any news on this, because it would be very useful to have markdown/html support in the description, so we can insert some bold text or even images? :)
