### ISSUE TITLE
Inform user: Is it anonymous?

### ISSUE THREAD

**Issue by Dubidubiduu** [nextcloud/forms#530]
**Nextcloud (please complete the following information):**
- Nextcloud-Version: 19.0.0
- Forms-Version: 2.0.0

**Is your feature request related to a problem? Please describe.**
Don't know if it's anonymous.

**Describe the solution you'd like**
Make it clear to the user if the form is anonymous.

**Comment by jancborchardt** [comment]
This is only necessary in the case when logged-in Nextcloud users open a form with their account. (Because non-logged in is by definition anonymous)

We can simply display some additional text after the "* Mandatory questions":
- When the "Anonymous responses" is checked, it would say "* Mandatory questions. Responses are anonymous."
- When the responses are not anonymous, it would say: "* Mandatory questions. Responses are connected to your Nextcloud account."

(And of course if there’s no mandatory questions, that part of the sentence wouldn’t be shown.)

**Comment by Dubidubiduu** [comment]
Thank you for your vastly fast answer. Mh, maybe I don't get it correctly?!

In my opinion it's not relevant if a question is mandatory or not. I care about if someone will know who I am, despite I'm answering an mandatory or an optional question.

And I think it's not about question at all, but about the whole form? So I would prefer a statement directly under the headline.

**Comment by skjnldsv** [comment]
@Dubidubiduu yes, that is what @jancborchardt said basically :)
He mentioned the Mandatory string because this is already below the headline, so let's put the anonymous warning right next to it

**Comment by jotoeri** [comment]
Mandatory is connected to the *, which only indicates specific questions. So maybe separate it a little bit from the mandatory-context.
Apart from that 👍

**Comment by jancborchardt** [comment]
Sure, it can also be put in a new line below that, but it makes sense to keep it close to the "Mandatory question" indicator text (and even in the same paragraph / style e.g.) cause it’s both additional meta info.

**Comment by jancborchardt** [comment]
If it’s less confusing we can just switch it around:
> Responses are connected to your Nextcloud account. An asterisk (*) indicates mandatory questions.

or

> Responses are anonymous. An asterisk (*) indicates mandatory questions.
