### ISSUE TITLE
Fill forms from Web and SMS 

### ISSUE THREAD

**Issue by zicmama** [nextcloud/forms#603]
**Nextcloud (please complete the following information):**
- Nextcloud-Version: [e.g. 19.0.0]
- Forms-Version: [e.g. 2.0.0-beta4]

I am using NextCloudPi
It is associated with a GSM/SMS card

I have shell scripting sending and receiving commands through SMS (a kind of question and form filling procedure).

How could I make your nextcloud "Form" plugin "backend" compatible with SMS dialog.
Do you have some SQL commands or curl API calls that will help interconnect our channels?

Thanks

**Comment by 42l-neil-tmp** [comment]
Hi,

Unfortunately it isn't easy to fill forms from command-line because you must send forms, questions and answers IDs to the API, and I believe there's no reliable API endpoint (from something like a public form URL) to get those IDs at the moment.

E.g. if you have a form with one question and three checkboxes, your browser will send something like this when you'll click Send: `{"formId":16,"answers":{"71":[120]}}`

- `16` is the form ID (which form you answered),
- `71` is the question ID (which question),
- `120` is the response ID (which option in the question).

If you know all those IDs beforehand while making your script (with defined questions and answers that won't change), then you can hardcode them in a script and send answers from commandline.

You'll have to handle the CSRF token and some cookies.

Here's a script that sends an answer to an empty form:

```bash
#!/bin/bash

# store cookies in a temporary file
COOKIE_FILE=cookie.txt
# NOTE: replace this number with your form ID here
FORM_ID=16

# getting the CSRF token and cookies.
# NOTE: replace the address below with your public form address
CSRF=`curl -s -c $COOKIE_FILE -X GET https://forms.42l.fr/apps/forms/PuBLiCT0K3NT22WB \
    | grep requesttoken | cut -d '"' -f2`

# sending the (empty) answer to the specified form ID with content-type and csrf token
# NOTE: replace the address below with your endpoint (just change the domain name)
POST_RESULT=`curl -s -b $COOKIE_FILE -X POST -H "Content-Type: application/json; charset=utf-8" \
    -H "requesttoken: $CSRF" --data '{"formId":'$FORM_ID',"answers":{}}' \
    https://forms.42l.fr/ocs/v2.php/apps/forms/api/v1/submission/insert`

# POST_RESULT and curl -v may help you to debug. 
# remove cookie file
rm $COOKIE_FILE
```

Note that this script will not work if your Forms version is under 2.0.4 (reworked API).
To answer non-empty forms with a script, edit it to include your questions and answers IDs. You can get them by answering the form yourself from a browser, then using F12 and take a look at the request data.

If you don't know those IDs beforehand, I'm afraid that you might have to scrap this data. Good luck.

I don't know how easier it is with SQL.

Hope it helps.

**Comment by jotoeri** [comment]
Hey Guys,

with the next release, we will now officially have a public API. So the manual CSRF-Handling won't be necessary anymore. You can find the docs here: https://github.com/nextcloud/forms/blob/master/docs/API.md

Greets! :)
Jonas
