### ISSUE TITLE
Inconsistent timestamp when exporting as csv

### ISSUE THREAD

**Issue by Emporea** [nextcloud/forms#606]
Forms: 2.0.4
Nextcloud 19.0.3

Steps to reproduce:

> When I go to Forms -> 3-dot Menu of Selected Form -> Select Responses -> Export to CSV (Summary tab selected) the time format is like this:  09/16/2020 1:02 AM
> 
> As soon as I hit the tab Responses and then again Export to CSV the time format is like this: 16.09.2020 01:02
> Even if i go back to the Summary tab.

Once I reload the Nextcloud Forms app via the app drawer it is back to the AM PM format.

So actually the wording "inconsistent" is quite misleading. It is consistent, but not the way I prefer. ;)

**Comment by skjnldsv** [comment]
cc @jotoeri any clue?

**Comment by jotoeri** [comment]
Hm, @ChristophWurst 
still moment initially shows english locale here. Do you maybe see, what i'm doing wrong...?

In Results, we just use the package and want to get a timestamp formatted. There's no more reference to moment, than these two.
https://github.com/nextcloud/forms/blob/6805f286c5c8e7eb0acff249acebb02079c4de53/src/views/Results.vue#L128
https://github.com/nextcloud/forms/blob/6805f286c5c8e7eb0acff249acebb02079c4de53/src/views/Results.vue#L273

- A debugging-`moment.locale()` returns me `en`, and correspondingly the date is formatted by `moment.format()`. I thought moment should know it's locale here already...?
- (`moment.unix(timestamp).format(...)` as you do it on mail, just does the same)
- (Loading the page from the edit-mode it works, but that is as the locale gets manually loaded there. But that now also seems like a workaround to me, as moment did not directly load its locale...)

**Comment by ChristophWurst** [comment]
> A debugging-`moment.locale()` returns me `en`

The one in your bundle or the global one in the browser?

**Comment by jotoeri** [comment]
From within the Results-page. So calling moment.locale() e.g. as reaction to any button upon the page..

**Comment by ChristophWurst** [comment]
> Results-page

Inside https://github.com/nextcloud/forms/blob/master/src/views/Results.vue?

**Comment by jotoeri** [comment]
Yep 👍

**Comment by ChristophWurst** [comment]
is the 24h format or the am/pm the expected format in your example?

**Comment by jotoeri** [comment]
My cloud's locale is German 'de', so i expect to get 24-hrs format : `Montag, 9. November 2020 14:45`
What i acutally get is am/pm format in english: `Monday, November 9, 2020 2:45 PM`

**Comment by jotoeri** [comment]
Hmm, two things - 
- @skjnldsv In https://github.com/nextcloud/forms/blob/bb2c6d92b33d6774a6adda07ce04a825e0501524/webpack.js#L19 we exclude the locales, which moment uses. I think you did that to have smaller bundles? When i remove this line, moment is able again to load a locale on results. And it seems like beeing the same problem on the new date-questions, where i can't access locale. Should we really load that everywhere manually, as you did in Sidebar? Or can't we just include them into the bundle again? There might be other ways to reduce bundle-sizes? :thinking:
- Second thing - if i disable this line, so moment can load a locale, moment seems to use the browsers locale. -> If i set my Cloud account to french, my browser is still german and moment returns german words instead of using the cloud-lanuage. That even happens on sidebar, where you manually load the locale... Still to handle.
