### ISSUE TITLE
line break in long text answers interferes with lines in exported CSV

### ISSUE THREAD

**Issue by Gorofad** [nextcloud/forms#683]
**Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!**

**Describe the bug**
When exporting answers to the csv file line breaks in long answers are translated into line breaks in the csv file. When importing the csv file afterwards in other programs like excel or origin every line break is seen as a new dataset. Thus it is not easily possible use the answers in other programs.

**To Reproduce**
1. create form with a question with a long answer
2. answer something with several line breaks (see first screenshot)
3. Look at the answers, the line breaks are removed in the overview (2nd screenshot)
4. export the answers as csv, the exported csv file has the line breaks (3rd screenshot)

**Expected behavior**
Line breaks should be changed to something like < br > or \n in the exported csv

**Nextcloud (please complete the following information):**
- Nextcloud-Version: 20.0.1
- Forms-Version: 2.0.4

**Screenshots**
![pic_01](https://user-images.githubusercontent.com/30502408/99183625-7b4c0500-273d-11eb-99d8-aa6c1150af64.PNG)
![pic_02](https://user-images.githubusercontent.com/30502408/99183634-961e7980-273d-11eb-95d3-5356ed61c74a.PNG)
![pic_03](https://user-images.githubusercontent.com/30502408/99183650-a8001c80-273d-11eb-9377-d7698838a7d5.PNG)

**Comment by jotoeri** [comment]
Hey @Gorofad,
the problem is, that csv is no standardized format, so when importing the data properly, excel just needs to check, how the data is formatted. It does not, if you just open the file! But if you use excels import functionality it works to import the text properly (_Excel: Data->Transform Data->From Text/CSV_)
The format we use is very common, other forms do so, too. So i think we won't change that.
Greets,
Jonas
