### ISSUE TITLE
iPhone Safari cutting off edge

### ISSUE THREAD

**Issue by jordan-richardo** [nextcloud/forms#684]
![image0](https://user-images.githubusercontent.com/36419398/99562428-13dcc200-2996-11eb-8451-6eca5f7bcace.png)
**Describe the bug**
When viewing the form from iphone Safari, the formatting cuts off on the right edge.

**To Reproduce**
View a form with Safari on Iphone

**Expected behavior**
The text to wrap to another line

**Screenshots**

**Nextcloud (please complete the following information):**
- Nextcloud-Version: 19.0.1
- Forms-Version:  2.0.4

**Smartphone (please complete the following information):**
 - Device: Iphone 10
 - Browser: Safari

I did not have direct access to the device unfortunately to get the requested detail.

**Comment by idecable** [comment]
I want to explore setting the submit button on the left side instead of the right side.

The problem has to do with the size of the font for the text input field. It make the web browser zoom in a little, and not possible to zoom out of it.. unless you go really at the bottom of that page and try to zoom out from there.

**Comment by jotoeri** [comment]
So - let's keep one issue to keep track of it. 😉
