### ISSUE TITLE
Hard to find settings sidebar

### ISSUE THREAD

**Issue by konfiv** [nextcloud/forms#717]
Thanks for the Form!

**Describe the bug**
When logged in in nextcloud and a form link is visited, not the form will show, but the files of the NextCloud.
If you are not logged in the form is visible and working.

**To Reproduce**
1. Limit the Form app to admin group
2. create a form
3. Login with a normal user
4. Paste the link provided by the form 
5. you will not see the form, but the files 

**Expected behavior**
When go to the form link, that the form will show, not the files of NextCloud.

**Screenshots**

**Nextcloud (please complete the following information):**
- Nextcloud-Version:  19.0.4
- Forms-Version: v2.0.4 (2020-09-01)

**Desktop (please complete the following information):**
 - OS: ubuntu 18.4
 - Browser firefox 
 - Version 68.10.0esr (64-Bit)

**Smartphone (please complete the following information):**

**Browser log**
```
Open your console, reload your page and/or do the action leading to this issue and copy/paste the log in this thread.
```

<details>
<summary>How to access your browser console (Click to expand)</summary>

# Chrome
- Press either CTRL + SHIFT + J to open the “console” tab of the Developer Tools.
- Alternative method:
    1. Press either CTRL + SHIFT + I or F12 to open the Developer Tools.
    2. Click the “console” tab.

# Safari
- Press CMD + ALT + I to open the Web Inspector.
- See Chrome’s step 2. (Chrome and Safari have pretty much identical dev tools.)

# IE9
1. Press F12 to open the developer tools.
2. Click the “console” tab.

# Firefox
- Press CTRL + SHIFT + K to open the Web console (COMMAND + SHIFT + K on Macs).
- or, if Firebug is installed (recommended):
    1. Press F12 to open Firebug.
    2. Click on the “console” tab.

# Opera
1. Press CTRL + SHIFT + I to open Dragonfly.
2. Click on the “console” tab.
</details>

**Additional context**

**Comment by skjnldsv** [comment]
Are you talking about filling the form? Or editing the form?
If the latest (editing), please check https://github.com/nextcloud/forms/issues/322
If the first (filling), then please double check your form sharing option and make sure the form is shared with your "normal user"

**Comment by konfiv** [comment]
Hi, thanks. I meant:
1) filling a form by people.
I did not want to share the edit form option, only filling a form. So, restricting to only fill a form is not possible?
In the App options, now I enabled share with my "normal user group" than the share link is working well, when users are logged in, and when not logged in.

**Comment by skjnldsv** [comment]
> 1. So, restricting to only fill a form is not possible?

Yes it is, on the sharing section, you can select which sharing scope you want to give:
![Capture d’écran_2020-12-16_11-45-10](https://user-images.githubusercontent.com/14975046/102338467-2bf33180-3f94-11eb-9401-31da2cc32984.png)

**Comment by konfiv** [comment]
Ok! Now found this "toggle settings" first time.
But "Share via link" was chosen. And my logged in users could not see the form, which was meant to fill. When not enabled under app settings "Limit to groups".

**Comment by skjnldsv** [comment]
@jancborchardt this is why the appsidebar icon needs to change :arrow_up: 
Any suggestions to improve this? This is indeed not discoverable

**Comment by RenataGegaj** [comment]
Also adding some input from the user testing round. Sharing the forms was one of the most challenging tasks for all participants.

### **Share form section**

<img width="341" alt="Screenshot 2022-01-20 at 23 30 26" src="https://user-images.githubusercontent.com/7413721/150432513-4da250d3-eaa0-4322-aac9-87347e4109bd.png">

_Screenshot 1: Share link button_



<img width="390" alt="Screenshot 2022-01-20 at 23 33 31" src="https://user-images.githubusercontent.com/7413721/150432842-b26666ff-86bc-4e4f-8058-a04f5c5d8bd7.png">

_Screenshot 2: Toggle Settings menu_

1. There were findability problems: Participants only used the "Share Link" button(Screenshot 1). They didn't explore the "Toggle Settings" menu and weren't aware of it. They were able to find it only after they were required to perform extra tasks related to sharing, such as "Share the form only with the students on your Nextcloud instance".
2. The content on the "Toggle Settings" menu confused participants during the sessions.  
- The "Share via link" option was understandable
The "Share Link" button there is redundant. There is the same button on the front page so I don't see the need for it to be placed under settings, the settings menu should be used only for adjusting user settings. 
- The "Show to all users of this instance" was confusing. They weren't sure if they clicked on it what would happen. They weren't sure if they'd need to take any steps to share it or it would appear automatically to users of the instance. Also, the word "Instance" is quite technical. There weren't any issues with it during the sessions since all participants were already familiar with Nextcloud even if they didn't particularly use Forms in the past, I'd expect this option to be confusing to a new user.

- "Choose users to share with" This option caused confusion as well. Similar to the above case, they weren't sure what the outcome will be. Will the form be shared automatically, will these users get a notification with the form there is no feedback to let the user know that the form has been shared(see screenshot 3). 
Also, I think there is a bug here. When a user is selected the dropdown menu remains active and it doesn't allow the user to see the list of participants they shared the form with.

<img width="396" alt="Screenshot 2022-01-21 at 00 28 20" src="https://user-images.githubusercontent.com/7413721/150438386-0ab1f915-8456-4429-b5fb-39040448e16a.png">

_Screenshot 3_


### **Settings section**

The menu options were easy to understand for all participants. The issue here was mainly on figuring out how they work and how they are related to the "Share form" section. For example, the "Allow multiple responses per person" option is already enabled by the system and it doesn't allow the user to enable/disable it. This happens only when the user has chosen the "Share via link" option. Most participants couldn't figure out the reasoning behind it and they were frustrated to find a disabled option(screenshot 4).

<img width="373" alt="Screenshot 2022-01-21 at 00 40 40" src="https://user-images.githubusercontent.com/7413721/150439483-6be9bd1c-9116-417a-afb5-992d14129cf9.png">

_Screenshot 4_

**Comment by jotoeri** [comment]
@jancborchardt @nimishavijay Any idea on how to solve that? Changing the Sidebar-Icon, maybe?
However, most probably useful to do on the vue-components then?

**Comment by jotoeri** [comment]
Ok. Thanks @nimishavijay for thinking about.

> Change the button text to just "Share" with a share icon and open the sidebar directly when you click on it. This could just be for the first time too when you're setting the share for the first time and after that it could be how it is now to easily copy the share link

That is basically done with the new Sharing now, so this more or less solves it for now on forms.

> A 3 dot menu icon instead of current sidebar icon. Since it's a generic icon and next to the "Share link" button, it seems more related to sharing

This one is then to do on the vue-components, i'll create an issue there.

Thus closing this issue as beeing resolved for the forms-specific part. :)
