### ISSUE TITLE
Choose different Seperator 

### ISSUE THREAD

**Issue by AnniT4S** [nextcloud/forms#742]
**Nextcloud (please complete the following information):**
- Nextcloud-Version: [ 20.0.5]
- Forms-Version: [e.g. 2.1. 0]

First of all: the app is great! 

Description: I am using large text fields in my survey. 
As Germans uses a lot of commas in their sentences I am having trouble when it comes to exports, because the seperator is a comma, too... 

**Describe the solution you'd like**
Is there a way to use e. g. the tabulator as separator? 

**Describe alternatives you've considered**
Would be nice to get other workarounds - just keep the answers per question together.

**Comment by jotoeri** [comment]
Hey @AnniT4S,

normally, that shouldn't be a problem, as text is wrapped into quotation marks. How do you use the data? Did you use some import functionality (e.g. in Excel), instead of just opening the file?
Currently there is no option to set a custom separator, nor it is planned until now.

Greets,
Jonas

**Comment by skjnldsv** [comment]
Should be fixed with #746 as it's properly escaped now

**Comment by AnniT4S** [comment]
> Hey @AnniT4S,
> 
> normally, that shouldn't be a problem, as text is wrapped into quotation marks. How do you use the data? Did you use some import functionality (e.g. in Excel), instead of just opening the file?
> Currently there is no option to set a custom separator, nor it is planned until now.
> 
> Greets,
> Jonas

Hi Jonas,
yes, I probably did. Thanks for the reply!
