### ISSUE TITLE
Confusing german translation for results button

### ISSUE THREAD

**Issue by stefan-niedermann** [nextcloud/forms#794]
@rakekniven i recently wanted to see the answers / results of a survey.
I was expected a button called `Ergebnisse` or `Auswertung` or something like that, but i wasn't able to find one.

The button turned out to be at the top right - the label says `Antworten` - i didn't notice / press it because i was afraid that it would lead to a page where i can fill out the survey as a user. I thought its meaning was `Reply`.

The translation should be adjusted to reduce the confusion :wink: 

![grafik](https://user-images.githubusercontent.com/4741199/108756654-175d8780-7549-11eb-8806-ec4746593503.png)

cc @jancborchardt for information

**Comment by jotoeri** [comment]
Hm, i think this is not only a translation problem... Just changing the translation of "Responses" will not match anymore e.g. for the tabs, where "Responses" really means the single Responses. So we would have to adapt the english version to for this. - Probably 'Results'?

**Comment by skjnldsv** [comment]
cc @jancborchardt

**Comment by rakekniven** [comment]
@stefan-niedermann Could you add a screenshot with english localisation as well. 

I am not a user of named app but try to help for sure.

**Comment by stefan-niedermann** [comment]
![Screenshot_20210227-232442_Fennec](https://user-images.githubusercontent.com/4741199/109402068-ff27a700-7952-11eb-8881-80176d14c1f3.png)

**Comment by rakekniven** [comment]
That's a "brutal" example to show that the devs need to provide context or even better comments on their code for the translators.
There are many occurences and now I think translations are wrong. See https://www.transifex.com/nextcloud/nextcloud/translate/#de_DE/forms/289550990?q=text%3Aresponses

For reference https://github.com/nextcloud/documentation/issues/5422

**Comment by jotoeri** [comment]
Hey @rakekniven, unfortunately, that only shifts the problem... The problem here is not a wrong translation of the word "Responses", but that in German the verb "antworten" and the Subject "Antworten" are not to distinguish (like "to respond" and "Responses").
With the changed translation, the wording does not match anymore within that Results-View, where one can choose between seeing a summary or seeing the single Responses (Both are the Results of the form!). For the latter, the term "Antworten" as translation for "Responses" is definitely reasonable, while selecting "Zusammenfassung" vs "Ergebnisse" within the view of Results does not match the actual behaviour.

- One thing, that just came into my mind: Do you as Translator see a similar word different, if there are different comments? So could you translate differently if we include separate comments for the use-cases? (I fear, this is not the case, as we also only get a json back without the comments? 🤔)

- Maybe my comment above, was a bit misleading: What i meant, was that we need to keep the translation "Antworten" as proper translation for "Responses", but need to change the english version of the Responses-Button (the one, that Stefan mentioned) to "Results", which will then be "Ergebnisse".

Greets! :)
Jonas


![grafik](https://user-images.githubusercontent.com/47433654/109415749-cde2c180-79ba-11eb-8c8c-f955589f3262.png)
