### ISSUE TITLE
And modules

### ISSUE THREAD

**Issue by ProgrammeRespirations** [nextcloud/forms#839]
**Nextcloud (please complete the following information):**
- Nextcloud-Version: 20.0.8
- Forms-Version: 2.2

I would like to insert in the form:
- descriptions
- links
- different parts
- titles

Thanks !

**Comment by jotoeri** [comment]
Hey @ProgrammeRespirations,

for Feature-Requests:
1. Please **search for existing issues**, before opening new ones. Maybe somebody else had the same idea before.
2. Please open **separate issues** for the topics that you did not find yet, so we can track and handle them separately.
3. Please use the **given template** and give us a detailed **description**, so we can implement what you want instead of what we guessed you want.

Therefore - Closing this for now.
Greets,
Jonas
