### ISSUE TITLE
Add Form Id in the export csv.

### ISSUE THREAD

**Issue by bademeister91** [nextcloud/forms#898]
- Nextcloud-Version: [16.0.0]
- Forms-Version: [1.0.3]

It would be helpful for formatting the csv-file, if you would add a id for each form that was filled (e.g. respondId). So for now this version has a "voteOptionId" for each question/option and an ongoing "Id" for each answer. But for multiple choice questions it would be helpful to have an Id for each filled form from one person.

For example if you add a checkbox question like this:

Question A: 
[x] Answer1
[x] Answer2
[x] Answer3

you get a csv file like this:
Question A        Answer1
Question A        Answer2
Question A        Answer3

In order to keep the information who gave this answer it would be helpful to get an Id for each filled form. Like this:

Question A        Answer1       1
Question A        Answer2       1
Question A        Answer3       1

The userid doesn't work like this for forms that get filled multiple times.

**Comment by jotoeri** [comment]
Hey @bademeister91,

thanks for taking the time here to write this nicely detailed feature request!
However, your Nextcloud-Version is a bit outdated and out of support since about a year. Same applies to version 1 of the forms app, which had a nearly full rewrite since v1. And i think on the current version 2 also your requested feature here should be solved, as the exported csv shows a completely new structure.
As such - i close this issue for now, and i can just highly recommend to update your cloud. 😉 

Greets!
Jonas 🙂
