### ISSUE TITLE
Bug occurs while viewing long text survey results 

### ISSUE THREAD

**Issue by aron9015** [nextcloud/forms#904]
When viewing survey results, long text response option answers lose their formatting including line breaks.

Nextcloud Forms Version 2.2.4

**Comment by jotoeri** [comment]
`white-space: pre-line` should do the trick, as on the form-description.

**Comment by jotoeri** [comment]
Yep, needs to remove the beautiful-code empty line... As on the description:
https://github.com/nextcloud/forms/blob/87dd08eb8479397fabc14d1c6b8e23db6ba0b240/src/views/Submit.vue#L36-L38

Alternatively v-text should also work instead of the curly-braces, as it's done on the infoMessage below... I'm just not sure which is the more common syntax there...

**Comment by skjnldsv** [comment]
We usually prefer moustache syntax as it's closer to the html standard (content within tags)
